on: [push]

jobs:
  buildbreaker:
    runs-on: ubuntu-latest
    name: Run Sorald Buildbreaker
    steps:
      - name: Checkout Sorald
        uses: actions/checkout@v2
        with:
          repository: 'SpoonLabs/sorald'
          ref: '5e64028cd82336b34a68c60d314ce1c57b4bf276'
          path: 'sorald'
      - name: Run Sorald Buildbreaker
        uses: slarse/test-github-action@e1f136ca4486dbf3f9afc15ca608e78ff2d3dc50
        with:
          source: 'src/main/java'
