on: [push]

jobs:
  buildbreaker:
    runs-on: ubuntu-latest
    name: Run Sorald Buildbreaker
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Checkout Sorald
        uses: actions/checkout@v2
        with:
          repository: 'SpoonLabs/sorald'
          ref: '5e64028cd82336b34a68c60d314ce1c57b4bf276'
          path: 'sorald'
      - name: Run Sorald Buildbreaker
        uses: ./
        id: sorald-buildbreaker
        with:
          source: 'sorald/src/main/java'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
